services:
  frontend:
    build: ./project-komisyon-portal
    ports:
      - "2626:2626"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080/api

  backend:
    build: ./project-komisyon-portal-backend
    ports:
      - "8080:8080"
    environment:
      MONGO_DB_CONNECTION: mongodb://mongo:27017/project-komisyon-portal
      PORT: 8080
      SALT_CODE: "ab276325"
      REDIS_URL: redis://redis:6379  
    depends_on:
      - mongo
      - redis 
    volumes:
      - backend-logs:/app/logs

  mongo:
    image: mongo
    ports:
      - "26026:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backup:
    image: mongo:6.0
    volumes:
      - D:/komisyon-portal_mongo-backup:/backup 
      - ./backup.sh:/app/backup.sh
    entrypoint: >
      /bin/sh -c "while true; do /app/backup.sh; sleep 3600; done"
    depends_on:
      - mongo

volumes:
  mongo-data:
  backend-logs:
  mongo-backup:
  redis-data:
