version: '3'

services:
  frontend:
    build: ./project-komisyon-portal
    ports:
      - "2626:2626" # 2626 kullanma sebebimiz adalet bakanlığı tarafından host makinede 80 portunun yasaklanmış olması
    depends_on:
      - backend # Frontend servisinin çalışabilmesi için backend servisinin çalışıyor olması gerekiyor
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080/api # Backend servisinin adresini belirtiyoruz

  backend:
    build: ./project-komisyon-portal-backend
    ports:
      - "8080:8080"
    environment:
      MONGO_DB_CONNECTION: mongodb://mongo:27017/project-komisyon-portal
      PORT: 8080
      SALT_CODE: "ab276325"
    depends_on:
      - mongo
    volumes:
      - backend-logs:/app/logs

  mongo:
    image: mongo
    ports:
      - "26026:27017"
    volumes:
      - mongo-data:/data/db

  backup:
    image: alpine
    volumes:
      - mongo-backup:/backup
      - ./backup.sh:/app/backup.sh # Yedekleme script'ini mount ediyoruz
    entrypoint: >
      /bin/sh -c "apk add --no-cache mongodb-tools && 
      while true; do /app/backup.sh; sleep 86400; done"
    depends_on:
      - mongo

volumes:
  mongo-data:
  backend-logs:
  mongo-backup:
